-- MySQL Script generated by MySQL Workbench
-- 10/24/16 22:48:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laravel-app
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `laravel-app` ;

-- -----------------------------------------------------
-- Schema laravel-app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel-app` DEFAULT CHARACTER SET utf8 ;
USE `laravel-app` ;

-- -----------------------------------------------------
-- Table `laravel-app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel-app`.`users` ;

CREATE TABLE IF NOT EXISTS `laravel-app`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `remember_token` VARCHAR(64) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel-app`.`account_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel-app`.`account_status` ;

CREATE TABLE IF NOT EXISTS `laravel-app`.`account_status` (
  `account_status_id` INT NOT NULL AUTO_INCREMENT,
  `account_status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_status_id`),
  UNIQUE INDEX `account_status_name_UNIQUE` (`account_status_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel-app`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel-app`.`country` ;

CREATE TABLE IF NOT EXISTS `laravel-app`.`country` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `country_code` VARCHAR(45) NOT NULL,
  `country_name` VARCHAR(45) NOT NULL,
  `country_flag` BLOB NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel-app`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel-app`.`states` ;

CREATE TABLE IF NOT EXISTS `laravel-app`.`states` (
  `states_id` INT NOT NULL AUTO_INCREMENT,
  `states_name` VARCHAR(45) NOT NULL,
  `states_code` VARCHAR(10) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`states_id`),
  INDEX `fk_states_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_states_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `laravel-app`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laravel-app`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laravel-app`.`patient` ;

CREATE TABLE IF NOT EXISTS `laravel-app`.`patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `date_birth` DATE NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `photo` BLOB NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip` VARCHAR(4) NULL,
  `states_id` INT NULL,
  `SSN` VARCHAR(255) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `remember_token` VARCHAR(64) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `last_login` TIMESTAMP NULL,
  `account_status_id` INT NOT NULL DEFAULT 1,
  `patient_col` VARCHAR(45) NULL,
  PRIMARY KEY (`patient_id`),
  INDEX `fk_patient_account_status_idx` (`account_status_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_patient_states1_idx` (`states_id` ASC),
  CONSTRAINT `fk_patient_account_status`
    FOREIGN KEY (`account_status_id`)
    REFERENCES `laravel-app`.`account_status` (`account_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_states1`
    FOREIGN KEY (`states_id`)
    REFERENCES `laravel-app`.`states` (`states_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
